train:
  experiment_name: IR_(CE,CE,CE)_(384,512) InceptionResnet_MS kfold
  augmentation: BaseAugmentation # "data augmentation type (default: BaseAugmentation)"
  batch_size: 256 # "input batch size for training (default: 64)"
  criterion1: cross_entropy # "criterion type (default: cross_entropy)"
  criterion2: cross_entropy # "criterion type (default: cross_entropy)"
  criterion3: cross_entropy # "criterion type (default: cross_entropy)"
  data_dir: /home/ubuntu/yj_study/baseline_v2/dataset/train/images # null
  dataset: MaskMultiLabelDataset # "dataset augmentation type (default: MaskBaseDataset)"
  epochs: 10 # "number of epochs to train (default: 1)"
  log_interval: 20 # "how many batches to wait before logging training status"
  lr: 0.0005 # "learning rate (default: 1e-3)"
  lr_decay_step: 20 # "learning rate scheduler decay step (default: 20)"
  model: InceptionResnet_MS # "model type (default: BaseModel)"
  model_dir: /home/ubuntu/yj_study/baseline_v2/model # null
  name: exp # "model save at {SM_MODEL_DIR}/{name}"
  optimizer: AdamP # null
  # scheduler: #CosineAnnealingLR
  #   value: 10
  resize: # "resize size for image when training"
    - 384
    - 512
  crop_size:
    - 320
    - 480
  seed: 41 # "random seed (default: 42)"
  val_ratio: 0.1 # "ratio for validaton (default: 0.2)"
  valid_batch_size: 16 # "input batch size for validing (default: 1000)"
  loss_rate: # loss 1 / loss 2 / loss 3
    - 4
    - 6
    - 10
  scheduler: "CosineAnnealingLR"
  dropout_p: 0.3
  classifier_num: 8
  num_folds: 10
  project: "mask_cls"
  entity: "cv17"
valid:
  batch_size: 256 # "input batch size for validing (default: 1000)"
  augmentation: BaseAugmentation
  resize: # "resize size for image when you trained (default: (96, 128))"
    - 384
    - 512
  crop_size:
    - 320
    - 480
  model: InceptionResnet_MS # "model type (default: BaseModel)"
  data_dir: /home/ubuntu/yj_study/baseline_v2/dataset/eval
  model_dir: /home/ubuntu/yj_study/baseline_v2/model/IR_(CE,CE,CE)_(384,512)_InceptionResnet_MS_kfold
  output_dir: /home/ubuntu/yj_study/baseline_v2/output
  dropout_p: 0.3
  classifier_num: 8
  num_folds: 10
