train:
  experiment_name: "Efficientnet_v2_1 - just run code-test"
  augmentation: BaseAugmentation # "data augmentation type (default: BaseAugmentation)"
  batch_size: 256 # "input batch size for training (default: 64)"
  criterion: label_smoothing # "criterion type (default: cross_entropy)"
  data_dir: /opt/ml/project/input/data/train/images # null
  dataset: MaskMultiLabelDataset # "dataset augmentation type (default: MaskBaseDataset)"
  epochs: 10 # "number of epochs to train (default: 1)"
  log_interval: 20 # "how many batches to wait before logging training status"
  lr: 0.001 # "learning rate (default: 1e-3)"
  lr_decay_step: 20 # "learning rate scheduler decay step (default: 20)"
  model: Efficientnet_v2_l # "model type (default: BaseModel)"
  model_dir: /opt/ml/project/Models # null
  name: exp # "model save at {SM_MODEL_DIR}/{name}"
  optimizer: AdamW # null
  resize: # "resize size for image when training"
    - 384
    - 512
  seed: 41 # "random seed (default: 42)"
  val_ratio: 0.2 # "ratio for validaton (default: 0.2)"
  valid_batch_size: 256 # "input batch size for validing (default: 1000)"
  patience: 3
valid:
  experiment_name: "Efficientnet_v2_1 - just_run_code-test"
  batch_size: 256 # "input batch size for validing (default: 1000)"
  resize: # "resize size for image when you trained (default: (96, 128))"
    - 384
    - 512
  model: InceptionResnet # "model type (default: BaseModel)"
  data_dir: /opt/ml/project/input/data/eval
  model_dir: /opt/ml/project/Models
  output_dir: /opt/ml/project/submission
