wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: Train avg loss
      6:
      - 3
      7:
      - 1
    - 1: Train F1-Score
      6:
      - 3
      7:
      - 2
    - 1: Validation avg loss
      6:
      - 3
      7:
      - 1
    - 1: Validation F1-Score
      6:
      - 3
      7:
      - 2
    python_version: 3.8.13
    start_time: 1666804080.041551
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 7
      - 16
      - 17
      - 23
      - 37
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
      10:
      - 3
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
image_size:
  desc: null
  value:
  - 512
  - 384
learning_rate:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: EfficientNet_b1
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: ReduceLROnPlateau
seed:
  desc: null
  value: 444
split_rate:
  desc: null
  value: 0.8
